runtime: nodejs18

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 5
  
env_variables:
  NODE_ENV: "production"
  OPENAI_API_KEY: "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"


